### ISSUE TITLE
Option to change the background (not square)

### ISSUE THREAD

**Issue by Diego-Franco** [ChaosLeong/PinView#1]
is Any option to add new method to change the background, maybe we can replace the square or the box just for a line

**Comment by ChaosLeong** [comment]
Sure, I will add this feature into next release. It may take two weeks.

**Comment by Diego-Franco** [comment]
Thank you, will be just like a line at the bottom or something, anyways, i'll try to do that and try to create a pull request. the only thing is sometimes canvas is weird to get it done lol

**Comment by ChaosLeong** [comment]
Great! Waiting for your good news.

**Comment by rajeevjaiswal** [comment]
@ChaosLeong  Any option to change the shape to vertical rectangle and also background color

**Comment by ChaosLeong** [comment]
@rajeevjaiswal There is no such feature at the moment

**Comment by ChaosLeong** [comment]
@parvendan There is no such feature at the moment, but it will become a new feature of the next release.

**Comment by ChaosLeong** [comment]
Please upgrade to version 1.2.0, and add `app:viewType="line"`
