### ISSUE TITLE
How Can i set Item background 

### ISSUE THREAD

**Issue by raj9686** [ChaosLeong/PinView#11]

**Comment by ismdcf** [comment]
Any update on this

**Comment by ChaosLeong** [comment]
@ismdcf I've planned to add this feature to the next release, hope I have time to do this

**Comment by serrokitskiy** [comment]
wait

**Comment by AdamGrzybkowski** [comment]
any update on this @ChaosLeong ?

**Comment by ChaosLeong** [comment]
Please upgrade to version 1.4.0.
