### ISSUE TITLE
Any way to fill in circles when user inputs pin?

### ISSUE THREAD

**Issue by raylee4204** [ChaosLeong/PinView#20]
Currently, there's gap between the stroke and the circle that gets drawn when user enters pin.

Is there any way to remove the gap?

Also, is there another option where we can have filled circles for default state and same look with different colour when pin is entered?

**Comment by ChaosLeong** [comment]
Can you provide a screenshot or xml code?

**Comment by raylee4204** [comment]
<img width="189" alt="screen shot 2018-05-02 at 11 02 16 am" src="https://user-images.githubusercontent.com/2085389/39531045-4be0083c-4df8-11e8-932f-a910919b209f.png">

**Comment by raylee4204** [comment]
The circles in the middle, can they fill up the whole space of outer square?

**Comment by ChaosLeong** [comment]
Sorry for late reply. And, no. If you want to add this feature, you can fork the project and make your own pinview.
