### ISSUE TITLE
Auto open keyboard

### ISSUE THREAD

**Issue by RJSDevel** [ChaosLeong/PinView#21]
Hi, do not work auto open  keyboard for view. I can't open implicit too.

**Comment by puneetflair** [comment]
Please fix this ASAP

**Comment by ChaosLeong** [comment]
@puneetflair @RJSDevel Sorry for late reply. Can you provide the PinView version number? I have tried to reproduce the issue on 1.3.2, but nothing happened.

**Comment by salmaanahmed** [comment]
I am working with version number 1.3.2 on Samsung C5 Pro. When clicking on pinview, sometimes keyboard doesn't shows up. It also happened on Google Pixel XL. Unable to find any specific scenario.

**Comment by squeeish** [comment]
Also not working on 1.4.2

**Comment by deepbhavsar** [comment]
I am using 1.4.2 but keyboard is not opening. emulator and some of device can open keyboard but redmi devices can't.

I have tried `pinView.requestFocus()` but unable to open keyboard

**Comment by mayankjain95** [comment]
The keyboard does not open when we change the orientation of the device.
Checked on version 1.4.2.
Is there any solution for this?

**Comment by ChaosLeong** [comment]
Please upgrade to version 1.4.3.
