### ISSUE TITLE
duplicate value for resource attr/itemBackground with config ''

### ISSUE THREAD

**Issue by mdadil2019** [ChaosLeong/PinView#26]
-I have added this library to my android project and everything was working fine until I added design support library ( 'com.android.support:design:27.1.1'), after adding this my gradle build failed with following error
 **Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed MyAppDirectory\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2489: error: duplicate value for resource 'attr/itemBackground' with config ''.**
 and when I remove the design support library dependency then everything becomes fine.

Complete problem description : https://stackoverflow.com/questions/51709716/android-resource-compilation-failed

**Comment by markspit93** [comment]
Most likely this is caused by this new attribute:

<attr name="itemBackground" format="reference|color" />

Looks like the same attribute already exists in the latest support library.
Renaming it should solve the issue.

**Comment by ChaosLeong** [comment]
@markspit93 Indeed, after doing some research, I found that `MenuView` (The Menu in the Toolbar) has defined this attribute.

``` xml
<declare-styleable name="MenuView">
    ...
    <!-- Default background for each menu item. -->
    <attr name="itemBackground" format="color|reference" />
    ...
</declare-styleable>
```

Therefore, in order to fix this issue, I will use `<attr name="android:itemBackground" />` instead of
`<attr name="itemBackground" format="reference|color" />`.

**Comment by ChaosLeong** [comment]
@mdadil2019 Please upgrade to 1.4.1.
