### ISSUE TITLE
Hiding pin lines when symbol entered

### ISSUE THREAD

**Issue by grine4ka** [ChaosLeong/PinView#27]
Hello, @ChaosLeong 

I have a proposal for a little enhancement. I think it's a usual UX that when you entered the symbol in PinView the line (or rectangle) under it is not drawn.

Something like on this image ![pin with no lines](https://cdn.pbrd.co/images/HAC5G7s.png)

Would you mind if I will realize that little feature through additional attribute?

**Comment by ChaosLeong** [comment]
Thanks for your advice, it is welcome to making a pull request.

**Comment by grine4ka** [comment]
I maked these )) #28

**Comment by ChaosLeong** [comment]
Merged
