### ISSUE TITLE
Set cursor visible

### ISSUE THREAD

**Issue by samurdhilbk** [ChaosLeong/PinView#3]
Is there a way to make a cursor appear on the current input box?

**Comment by gmm932** [comment]
same function need

**Comment by lnj721** [comment]
How to clear input content one time

**Comment by ChaosLeong** [comment]
@lnj721 Have you tried the `setText("")`?

**Comment by lnj721** [comment]
it does't work.Finnaly I add a method in thie  class PasswordInput

    public void clearText(){
        setText(null);
        moveCursorToTheEnd();
        currTextLen = 0;
        final ValueAnimator scanAnim;
        final ValueAnimator alphaAnim;
        scanAnim = ValueAnimator.ofFloat(1F, 0F);
        alphaAnim = ValueAnimator.ofInt(255, 0);
        scanAnim.setDuration(750);
        scanAnim.setRepeatCount(0);
        scanAnim.setInterpolator(new OvershootInterpolator());
        scanAnim.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                float scale = (float) valueAnimator.getAnimatedValue();
                for (int i=0;i<boxCount;i++){
                    scans[i] = scale;//执行后都变成了0
                }
                postInvalidate();
            }
        });
        alphaAnim.setDuration(750);
        alphaAnim.setRepeatCount(0);
        alphaAnim.setInterpolator(new LinearInterpolator());
        alphaAnim.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                int alpha = (int) valueAnimator.getAnimatedValue();
                for (int i=0;i<boxCount;i++){
                    alphas[i] = alpha;
                }
                postInvalidate();
            }


        });
        scanAnim.start();
        alphaAnim.start();

    }

**Comment by ChaosLeong** [comment]
Please upgrade to 1.3.0 and add `android:cursorVisible="true"`
