### ISSUE TITLE
How to enable copy-paste option ?

### ISSUE THREAD

**Issue by passiondroid** [ChaosLeong/PinView#31]
Question. 
Copy paste functionality not working in pinview even setting
android:textIsSelectable="true" on the com.chaos.view.PinView

**Comment by ChaosLeong** [comment]
Because PinView is not allowed to copy and paste, this is achieved by `setTextIsSelectable(false)` in constructor and override the `getDefaultMovementMethod()`.

If you really need to enable copy and paste, you can start with these.

**Comment by imran-cse11** [comment]
Can't understand how to enable paste option. Please give me a example.
