### ISSUE TITLE
Android x support not working with 1.4.2

### ISSUE THREAD

**Issue by gevariya-ajit** [ChaosLeong/PinView#39]
What kind of issue is this?
Latest version 1.4.2 is not working with AndoridX support libraries. 
##### Info:

 * PinView version: 1.4.2

**Comment by softmarshmallow** [comment]
Same here.

**Comment by rafaeltoledo** [comment]
Pull Request #38 was merged but not released yet

**Comment by ChaosLeong** [comment]
Please upgrade to version 1.4.3.
