### ISSUE TITLE
Highlight current item

### ISSUE THREAD

**Issue by jecomas** [ChaosLeong/PinView#5]
Is there a way to highlight current pin item? it's to know what item is focused.

**Comment by ChaosLeong** [comment]
Currently, there is no way to highlight single item. But this feature will be added to the next release.

**Comment by ChaosLeong** [comment]
Please upgrade to 1.3.0, add `android:state_selected="true"` to `app:lineColor`

``` xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Use for the item to be input, set the value as the default to disable it -->
    <item android:color="@color/line_selected" android:state_selected="true" />
    <item android:color="@color/line_focused" android:state_focused="true" />
    <item android:color="@color/line_default" />
</selector>
```

or add `android:cursorVisible="true"`.
