### ISSUE TITLE
viewType line isn't a straight line

### ISSUE THREAD

**Issue by lorenzowoodridge** [ChaosLeong/PinView#7]
For some reason using viewType="line" does not produce a line, but has some odd coloring on the sides. Below is the snippet of code I am using as well as a screenshot

`<com.chaos.view.PinView
        android:id="@+id/pinView"
        style="@style/PinWidget.PinView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:inputType="number"
        android:singleLine="true"
        app:itemCount="6"
        app:lineWidth="2dp"
        app:viewType="line" />`

![screen shot 2017-12-22 at 10 21 30 am](https://user-images.githubusercontent.com/24234326/34306749-0181b612-e702-11e7-8b3b-3f348b377ae3.png)

**Comment by ChaosLeong** [comment]
Hi @lorenzowoodridge , add `app:itemRadius="0dp"` to fix the bug in current version.
And this bug will be fixed in next release.

**Comment by ChaosLeong** [comment]
The issue has been fixed in version 1.3.0.
