### ISSUE TITLE
 Arabic its not working

### ISSUE THREAD

**Issue by shidhin** [ChaosLeong/PinView#9]
I have the same issue. In Arabic its not working, why? Here is my question

[https://stackoverflow.com/questions/48438534/pinview-not-showing-for-arabic-language](https://stackoverflow.com/questions/48438534/pinview-not-showing-for-arabic-language)

**Comment by ChaosLeong** [comment]
Because PinView does not currently support RTL, I will fix it this weekend.

**Comment by shidhin** [comment]
Thnaks.

**Comment by ChaosLeong** [comment]
Please upgrade to version 1.3.0.
